//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int ID { get; set; }
        public Nullable<int> Userprofile { get; set; }
        public string Content { get; set; }
        public int Author { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Profiles Profiles { get; set; }
    }
}
